name: FirstActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allows to trigger from external webhooks
  repository_dispatch:
      types: [dependency_update]

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
        - name: step 1
          uses: actions/checkout@v2
        - name: step 2
          run: env | sort
        - name: step 2-1
          uses: actions/setup-java@v2
          with:
              distribution: 'adopt-openj9' 
              java-version: '8'
        - name: step 3
          uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
        - name: step 4
          run: atlas-version
        - name : create a touch file
          run: touch welcome
        - name: upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            name: linux
            path: ./welcome
  job2:
    name: second job
    runs-on: windows-latest
    steps:
        - name: step 1
          uses: actions/checkout@v2
        - name: step 2
          run: "Get-ChildItem Env: | Sort-Object Name"
