name: FirstActions

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
        - name: step 1
          uses: actions/checkout@v2
        - name: step 2
          run: env | sort
        - name: step 2-1
          uses: actions/setup-java@v2
          with:
              distribution: 'adopt-openj9' 
              java-version: '8'
        - name: step 3
          uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
        - name: step 4
          run: java -cp java HelloWorldApp
  job2:
    name: second job
    runs-on: windows-latest
    steps:
        - name: step 1
          uses: actions/checkout@v2
        - name: step 2
          run: "Get-ChildItem Env: | Sort-Object Name"
