name: use docker image

on: push
#  workflow_dispatch:

jobs:
  job1:
    name: Check atlassian sdk env
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sudh33r/alpineatlassiansdk:v1
      credentials:
        username: ${{secrets.GHCR_USER}}
        password: ${{secrets.GHCR_TOKEN}}
    steps:
      - name: step 1
        uses: actions/checkout@v2
      - name: change to root user and check atlas version
        run: |
          pwd
          ls -lrt
          uname -a
          cat /etc/os-release
          source /root/.profile
          atlas-version
       
