name: Summary of workflow

on:
  workflow_dispatch:

jobs:
  summarize:

    runs-on: ubuntu-latest

    steps:
    - name: Write to workflow job summary
      run: |
        SUMMARY=$'# Testing Job Summary\n## Second Level Heading\nHello GitHub'
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
        echo '---' >> $GITHUB_STEP_SUMMARY
        echo '|key|repo|type|' >> $GITHUB_STEP_SUMMARY
        echo '|---|---|---|' >> $GITHUB_STEP_SUMMARY
        echo '|global|test|normal|' >> $GITHUB_STEP_SUMMARY
        echo "testing" >> $GITHUB_STEP_SUMMARY
